// XState 상태 머신 타입 — state-machine.json 스키마 기반

// 상태 머신 상태 목록 (15개 + 모바일)
export const MACHINE_STATES = {
  IDLE: "IDLE",
  SPEC_ANALYSIS: "SPEC_ANALYSIS",
  POLICY_CHECK: "POLICY_CHECK",
  GATE_PLAN_APPROVAL: "GATE_PLAN_APPROVAL",
  PLANNING: "PLANNING",
  GATE_TOOL_APPROVAL: "GATE_TOOL_APPROVAL",
  CODE_GENERATION: "CODE_GENERATION",
  CODE_REVIEW: "CODE_REVIEW",
  GATE_APPLY_CHANGES: "GATE_APPLY_CHANGES",
  APPLY_CHANGES: "APPLY_CHANGES",
  TESTING: "TESTING",
  GATE_DEPLOY: "GATE_DEPLOY",
  DEPLOY_EXECUTE: "DEPLOY_EXECUTE",
  COMPLETED: "COMPLETED",
  DENIED: "DENIED",
  ERROR_RECOVERY: "ERROR_RECOVERY",
  EMERGENCY_STOP: "EMERGENCY_STOP",
  AWAITING_USER_INPUT: "AWAITING_USER_INPUT",
  MOBILE_ACTION_EXECUTION: "MOBILE_ACTION_EXECUTION",
} as const;

export type MachineState = typeof MACHINE_STATES[keyof typeof MACHINE_STATES];

// 상태 머신 이벤트 목록
export const MACHINE_EVENTS = {
  USER_REQUEST: "USER_REQUEST",
  SPEC_COMPLETE: "SPEC_COMPLETE",
  SPEC_NEED_CLARIFICATION: "SPEC_NEED_CLARIFICATION",
  ALLOW: "ALLOW",
  CONSTRAINED_ALLOW: "CONSTRAINED_ALLOW",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  DENY: "DENY",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SCOPE_MODIFIED: "SCOPE_MODIFIED",
  TIMEOUT: "TIMEOUT",
  PLAN_COMPLETE: "PLAN_COMPLETE",
  PLAN_NEEDS_TOOLS: "PLAN_NEEDS_TOOLS",
  NO_CODE_NEEDED: "NO_CODE_NEEDED",
  CODE_COMPLETE: "CODE_COMPLETE",
  REVIEW_PASS: "REVIEW_PASS",
  REVIEW_BLOCKERS: "REVIEW_BLOCKERS",
  APPLY_SUCCESS: "APPLY_SUCCESS",
  APPLY_FAILED: "APPLY_FAILED",
  TEST_PASS: "TEST_PASS",
  TEST_FAIL: "TEST_FAIL",
  SKIPPED: "SKIPPED",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  RECOVERY_SUCCESS: "RECOVERY_SUCCESS",
  RECOVERY_FAILED: "RECOVERY_FAILED",
  USER_RESPONSE: "USER_RESPONSE",
  CANCEL: "CANCEL",
  MOBILE_ACTION_SUCCESS: "MOBILE_ACTION_SUCCESS",
  MOBILE_ACTION_FAILED: "MOBILE_ACTION_FAILED",
  MOBILE_DEVICE_DISCONNECTED: "MOBILE_DEVICE_DISCONNECTED",
} as const;

export type MachineEvent = typeof MACHINE_EVENTS[keyof typeof MACHINE_EVENTS];
